trigger:
- master

jobs:
- job: Scan
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: Build
  steps:
  - script: |
      docker run -it anchore/engine-cli anchore-cli
    displayName: 'Scan image with Anchore'