trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: docker build -t jvalance/node_critical_fail .
  displayName: 'Build Docker image'

- script: docker push jvalance/node_critical_fail
  displayName: 'Push Docker image'
