trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'


steps:
- script: |
    apt-get install python-pip
    pip install anchorecli
    docker login -u $(dockerhubUser) -p $(dockerhubPass)
  displayName: 'Build and push Docker image'