trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'


steps:
- script: |
    sudo apt-get install python-setuptools
    pip install anchorecli
    docker login -u $(dockerhubUser) -p $(dockerhubPass)
  displayName: 'Build and push Docker image'